[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo", "php83Extensions.pdo_mysql", "php83Extensions.mbstring", "php83Extensions.xml", "php83Extensions.curl", "php83Extensions.zip", "php83Extensions.gd", "php83Extensions.intl", "php83Extensions.bcmath", "php83Extensions.tokenizer", "php83Extensions.ctype", "php83Extensions.fileinfo", "php83Extensions.openssl", "composer"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = []

[start]
cmd = "touch database/database.sqlite && php artisan config:clear && php artisan cache:clear && php artisan view:clear && php artisan route:clear && php artisan storage:link --force && php artisan migrate:fresh --force && php artisan db:seed --force && php -S 0.0.0.0:${PORT:-8080} -t public"
